### ISSUE TITLE
A minor issue...

### ISSUE THREAD

**Issue by abordoli** [CyaNox/Noxys_Fading#1]
There is a swap on the mouse-roll overs between "Building Remnant Fading Time" and "Rail Remnant Fading Time". It makes me, for one, not want to mess with the settings since they each have different maximums and I'm not sure if it's just the roll-over that is swapped or the input field too.
Regards,
~B

P.S. Hope all is well!

**Comment by NoxyNixie** [comment]
Ah nice catch I'll fix this soonish (I just got back from a 3 week vacation so have to catch up a bit).

The setting name is correct so where the setting name says rail it is about the rail.

**Comment by abordoli** [comment]
Are you on Discord? I've got one with Nexela an Earendel to collaborate on stuff...
Discord - Free voice and text chat for gamers
  
|  
|   
|   
|   |    |

   |

  |
|  
|   |  
Discord - Free voice and text chat for gamers
 Step up your game with a modern voice & text chat app. Crystal clear voice, multiple server and channel supp...  |   |

  |

  |

**Comment by NoxyNixie** [comment]
I hardly use discord. Your message is kind of scrambled on github. What is your question?
