### ISSUE TITLE
About using "Bob's Enemies" together

### ISSUE THREAD

**Issue by murakotaro4** [CyaNox/Noxys_Fading#2]
Hello
I adjust the time until the dead body of the bitter disappears.
I am using Bob's Enemies.
It takes time for some nests and bitters to disappear.
Will you update it so that it can be used with Bob's mod?

**Comment by NoxyNixie** [comment]
As far as I'm aware all of bobs biters, spitters and spawners are supported already.

If it isn't working then what are your settings?

**Comment by murakotaro4** [comment]
my setting
![20180418195940_1](https://user-images.githubusercontent.com/7923699/38928234-1712f926-4343-11e8-8850-702426d7873f.jpg)



When I defeat the nest of "Elemental" spawner, it will not disappear immediately like a picture.

before
![20180418194400_1](https://user-images.githubusercontent.com/7923699/38927794-d61e35c6-4341-11e8-95ef-69ca8d1ddac4.jpg)
after
![20180418194410_1](https://user-images.githubusercontent.com/7923699/38927799-d8deacaa-4341-11e8-9c2b-84fc4943eeb9.jpg)

Bitters, worms etc added by Bob's such as "Big fire worm" will not disappear soon. Vanilla's bitter etc will disappear soon.
![20180418195418_1](https://user-images.githubusercontent.com/7923699/38928114-c4abfe1c-4342-11e8-8829-969f4f340060.jpg)
![20180418195518_1](https://user-images.githubusercontent.com/7923699/38928121-c7aa8f48-4342-11e8-8124-5af4fdbd1506.jpg)
